# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('on_channel_time', models.DateTimeField()),
                ('time_of_relieve', models.DateTimeField()),
                ('hours_on_break', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_schedule.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('positions', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='position_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_schedule.Unit'),
        ),
    ]
