# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_schedule', '0004_auto_20180701_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(default='Ax', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='positions',
            field=models.CharField(max_length=30),
        ),
    ]
