# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_schedule', '0005_auto_20180706_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
